name = "ImmersiveCMP"
author = "Sam302rk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84b1ab2e10e0103fa90058546d24ab799b6d754dbc7ac5c5319399bac6be6ccf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
